### ISSUE TITLE
Scale to single 64x32?

### ISSUE THREAD

**Issue by jimmyeao** [bogd/esp32-morphing-clock#2]
Anyway this can scale to a single 64x32 Matrix? I changed the size in config.h, but everything is clipped or overwritten.
Great project by the way :)

**Comment by jimmyeao** [comment]
[https://github.com/jimmyeao/esp32-morphing-clock](https://github.com/jimmyeao/esp32-morphing-clock)
Managed to shift a few things around to make it fit on a smaller display, sacrificed the 5 day forecast and MQTT Readings
Maybe it needs to have "Pages" on the lower half of the screen so it can flip between Date & Lo/Hi temp to Forecast and sensors
![IMG_5742](https://github.com/bogd/esp32-morphing-clock/assets/5197831/078ca7ea-4eb3-4a47-80c6-c1250ca49f51)

**Comment by bogd** [comment]
My apologies, I didn't see the issue in time (I missed the notification). 

As you have already figured out, getting everything to fit into a smaller matrix will require some resizing. 

Quick hint - you can also resize the weather icons. I have enlarged them by a factor of two to make them more readable on the larger matrix - but you can just draw them at their original size by calling `drawBitmap` with `enlarged=false` (in `weather.cpp`, `drawWeatherIcon`)

**Comment by jimmyeao** [comment]
Awesome, thanks :)
